version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: petstay
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - petstay_app-network

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=petstay
    ports:
      - "8080:8080"
    networks:
      - petstay_app-network

networks:
  petstay_app-network:
    driver: bridge

volumes:
  mysql-data:
